default_language_version:
  python: python3.8

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-json
      - id: check-added-large-files
      - id: detect-private-key
      - id: detect-aws-credentials
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [ --py37-plus ]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [--settings-path=pyproject.toml]

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
